#! /usr/bin/zsh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
polybar example &


bspc monitor -d 1 2 3
bspc config window_gap          15
bspc config focus_follows_pointer	true
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding		6
bspc config bottom_padding	6
bspc config right_padding	6
bspc config left_padding	6
